<a href="https://colab.research.google.com/github/Tahmidro/Deep-Learning-Notebooks-Learning-phase-/blob/main/perceptron_implemantation_from_scratch_for(_or%2Cand)_gates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
import pandas as pd

In [69]:
class Perceptron:
  def __init__(self, eta, epochs):
    self.eta = eta
    self.epochs = epochs
    random=np.random.seed(1)
    self.weights=np.random.randn(3)*1e-4
    print(f"initial weights:{self.weights}")

  def activation(self,inputs,weights):
    z=np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X=X
    self.y=y
    for epoch in range(self.epochs):
      print(f"epoch:{epoch}")
      yHat=self.activation(self.X,self.weights)
      print(f"predicted value:{yHat}")
      error=self.y-yHat
      print(f"error:{error}")
      self.weights=self.weights+self.eta*np.dot(self.X.T,error)
      print(f"updated weights:{self.weights}")
      print("#####")

  def predict(self,X):
    return self.activation(X,self.weights)

In [70]:
And = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,0,0,1]
}
And=pd.DataFrame(And)

X=And.drop(["y"],axis=1)
y=And["y"]
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [71]:
XwithBias=np.c_[X,-np.ones(len(X))]
XwithBias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [72]:
model=Perceptron(eta=0.1,epochs=10)
model.fit(XwithBias,y)

initial weights:[ 1.62434536e-04 -6.11756414e-05 -5.28171752e-05]
epoch:0
predicted value:[1 0 1 1]
error:0   -1
1    0
2   -1
3    0
Name: y, dtype: int64
updated weights:[-9.98375655e-02 -6.11756414e-05  1.99947183e-01]
#####
epoch:1
predicted value:[0 0 0 0]
error:0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:2
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:3
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:4
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:5
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:6
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:7
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:8
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:9
predicted value:[0 0 0 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####

In [73]:
model.predict(XwithBias)

array([0, 0, 0, 1])

In [74]:
OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" : [0,1,1,1]
}
OR=pd.DataFrame(OR)

X=OR.drop(["y"],axis=1)
y=OR["y"]
y.to_frame()

   y
0  0
1  1
2  1
3  1

In [75]:
model=Perceptron(eta=0.1,epochs=10)
model.fit(XwithBias,y)

initial weights:[ 1.62434536e-04 -6.11756414e-05 -5.28171752e-05]
epoch:0
predicted value:[1 0 1 1]
error:0   -1
1    1
2    0
3    0
Name: y, dtype: int64
updated weights:[ 1.62434536e-04  9.99388244e-02 -5.28171752e-05]
#####
epoch:1
predicted value:[1 1 1 1]
error:0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.00016243 0.09993882 0.09994718]
#####
epoch:2
predicted value:[0 0 0 1]
error:0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights:[ 0.10016243  0.19993882 -0.10005282]
#####
epoch:3
predicted value:[1 1 1 1]
error:0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[ 1.00162435e-01  1.99938824e-01 -5.28171752e-05]
#####
epoch:4
predicted value:[1 1 1 1]
error:0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####
epoch:5
predicted value:[0 1 1 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####
epoch:6
predicted value:[0 1 1 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####
epoch:7
predicted value:[0 1 1 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####
epoch:8
predicted value:[0 1 1 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####
epoch:9
predicted value:[0 1 1 1]
error:0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights:[0.10016243 0.19993882 0.09994718]
#####

In [76]:
model.predict(XwithBias)

array([0, 1, 1, 1])